server:
  port: 8001

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ticket_booking

mongock:
  enabled: true
  change-logs-scan-package: epam.patiem.ticketbooking.db


logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
    net:
      sf:
        ehcache=debug: